
SHOW DATABASES;
USE companyDB;

CREATE TABLE Employee (
    EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL
);

INSERT INTO Employee VALUES
(1, 'Amit', 'Verma', 'HR', 60000.00),
(2, 'Neha', 'Sharma', 'Finance', 130000.00),
(3, 'Rajesh', 'Gupta', 'IT', 90000.00),
(4, 'Kavya', 'Reddy', 'Marketing', 115000.00),
(5, 'Arun', 'Nair', 'HR', 75000.00),
(6, 'Sneha', 'Mehta', 'IT', 108000.00),
(7, 'Rohit', 'Malhotra', 'Admin', 240000.00),
(8, 'Meera', 'Iyer', 'Finance', 125000.00);

SELECT * FROM Employee;
SELECT * FROM Employee WHERE DEPARTMENT = 'IT' AND SALARY > 100000;
SELECT * FROM Employee WHERE DEPARTMENT = 'HR' OR SALARY < 80000;
SELECT * FROM Employee WHERE NOT DEPARTMENT = 'Finance';
SELECT * FROM Employee WHERE SALARY > 80000 AND (DEPARTMENT = 'IT' OR DEPARTMENT = 'Finance');
SELECT * FROM Employee WHERE EMP_ID IN (1,5,6,8) AND SALARY >= 10000;
SELECT * FROM Employee WHERE EMP_ID NOT IN (2,4,6,8);
SELECT * FROM Employee WHERE DEPARTMENT NOT IN ('HR', 'Admin') AND SALARY BETWEEN 70000 AND 300000;
SELECT * FROM Employee WHERE FIRST_NAME LIKE 'R%' AND SALARY >= 200000;
SELECT * FROM Employee WHERE DEPARTMENT NOT IN ('Admin') AND SALARY < 100000;
SELECT MIN(SALARY) AS Minimum_Salary FROM Employee;
SELECT * FROM Employee WHERE SALARY = (SELECT MAX(SALARY) FROM Employee);
SELECT AVG(SALARY) AS Avg_Admin_Salary FROM Employee WHERE DEPARTMENT = 'Admin';
SELECT SUM(SALARY) AS Total_HR_Admin_Salary FROM Employee WHERE DEPARTMENT IN ('HR', 'Admin');
SELECT COUNT(*) AS Count_R FROM Employee WHERE FIRST_NAME LIKE 'R%';
SELECT SUM(SALARY) AS Total_Salary_Range FROM Employee WHERE SALARY BETWEEN 50000 AND 200000;
SELECT FIRST_NAME FROM Employee UNION SELECT LAST_NAME FROM Employee;
SELECT FIRST_NAME, SALARY,
    CASE
        WHEN SALARY < 50000 THEN 'Poor'
        WHEN SALARY BETWEEN 50000 AND 150000 THEN 'Middle Class'
        ELSE 'Rich'
    END AS StatusBasedOnSalary
FROM Employee;
